name = "axis-trigger"
main = "src/server.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
NODE_ENV = "production"
ASSET_CONFIG_FILE = "assets.json"

[[d1_databases]]
binding = "DB"
database_name = "axis_trigger"
database_id = "df225f07-9768-4595-89a0-3823a45698cf"

[triggers]
crons = ["0 * * * *"]  # run every hour