name = "axis-trigger"
main = "src/server.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]
account_id = "d637410df2e8f923e3fe6b63955a283b"

[observability]
enabled = true

[vars]
NODE_ENV = "production"
ASSET_CONFIG_FILE = "assets.json"
CRON_BACKFILL_DAYS = "30"
CG_CONCURRENCY= "6"

[[d1_databases]]
binding = "DB"
database_name = "axis_trigger"
database_id = "df225f07-9768-4595-89a0-3823a45698cf"

[triggers]
crons = ["0 */3 * * *"]

[[kv_namespaces]]
binding = "CACHE"
id = "28a5135943f54d82af9b227eee4fb834"
