name = "axis-trigger"
main = "src/server.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
NODE_ENV = "production"
ASSET_CONFIG_FILE = "assets.json"


